CREATE TABLE artist (
id INT NOT NULL AUTO_INCREMENT,
firstname VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
description  VARCHAR(255) NOT NULL,
photo VARCHAR(100) NOT NULL,
PRIMARY KEY (`id`));

CREATE TABLE artwork (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
description  VARCHAR(255) NOT NULL,
photo VARCHAR(100) NOT NULL,
id_artist  INT NOT NULL,
PRIMARY KEY (`id`));

CREATE TABLE gallery (
id_user INT NOT NULL,
id_artwork INT NOT NULL,
PRIMARY KEY (id_user, id_artwork));

CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
firstname VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
mail VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
is_admin TINYINT DEFAULT 0 NOT NULL,
PRIMARY KEY (`id`));